version: 0.2
env:
  shell: bash
  variables:
    TERRAFORM_DOWNLOAD_URL: https://releases.hashicorp.com/terraform/1.1.3/terraform_1.1.3_linux_amd64.zip

phases:
    install:
      runtime-versions:
        nodejs: 16
      commands:
        - echo "instaling node"
    pre_build:
      commands:
        - cd $CODEBUILD_SRC_DIR
        - ls -la
        - cp -Rp . /tmp
        - cd /tmp
        - echo "we are inside tmp"
        - ls -la
        - echo "we are in pre built phase"
    build:
      commands:
        - echo "we are in build block"
        - node -v
        - npm install
        - echo "nothing to build continue"
    post_build:
      commands:
        - echo "post build done"
        - apt-get install -y curl jq unzip
        - wget $TERRAFORM_DOWNLOAD_URL
        - unzip -o terraform_1.1.3_linux_amd64.zip
        - mv terraform /bin
        - rm terraform_1.1.3_linux_amd64.zip
        - terraform -v
        - export BUILD_OUTPUT_ARTIFACTS="/buildoutputartifacts"
        - ln -s $CODEBUILD_SRC_DIR_buildOutput $BUILD_OUTPUT_ARTIFACTS
        - ls $BUILD_OUTPUT_ARTIFACTS
        - terraform init
        - terraform plan -out="dev.tfplan"
        - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'
  base-directory: dist
